### ISSUE TITLE
Chapter 2 plots are missing regression line

### ISSUE THREAD

**Issue by jasonsalas** [PacktPublishing/Keras-2.x-Projects#1]
Hello!  I'm replicating the code samples from the Chapter 2 of the book, and in these blocks, comparing a multilayer perceprtron in Keras against scikit-learn's LinearRegression model, the produced plots don't generate the regression lines, as in the book's illustrations:

plt.figure(1)
plt.subplot(121)
plt.scatter(Y_test, Y_predKM)
plt.xlabel("Actual values")
plt.ylabel("Predicted values")
plt.title("Keras Neural Network Model")

plt.subplot(122)
plt.scatter(Y_test, Y_predLM)
plt.xlabel("Actual values")
plt.ylabel("Predicted values")
plt.title("SKLearn Linear Regression Model")
plt.show()

Thanks for looking into it! :)

**Comment by CiaburroGiuseppe** [comment]
Hi Jason,
first of all, thank you for buying my book.
I highlighted the lines in the graphs to make the comparison between the two models more comprehensible. However, the same result can be obtained by adding the following line of code:

**plt.plot(Y_test,Y_test)**

So the block of code highlighted by you becomes:

plt.figure(1)
plt.subplot(121)
plt.scatter(Y_test, Y_predKM)
plt.plot(Y_test,Y_test)
plt.xlabel("Actual values")
plt.ylabel("Predicted values")
plt.title("Keras Neural Network Model")

plt.subplot(122)
plt.scatter(Y_test, Y_predLM)
plt.plot(Y_test,Y_test)
plt.xlabel("Actual values")
plt.ylabel("Predicted values")
plt.title("SKLearn Linear Regression Model")
plt.show()

I hope I was helpful.

**Comment by jasonsalas** [comment]
Thanks much! :)
