### ISSUE TITLE
Chapter03, Chapter 04 code typo in github

### ISSUE THREAD

**Issue by hygjob** [PacktPublishing/Keras-2.x-Projects#3]
Hello I'm Paul.

I love to read your book - KERAS 2X Projects
You explain concept easily and show how to implement Keras code that easily understanding.
But there are some code to modify so I write this issue.

In chater03

Data = pd.read_excel('ClevelandData.xlsx', names=HDNames)
=>Data = pd.read_excel('Ch3.ClevelandData.xlsx', names=HDNames)

In chapter04

Data = pd.read_excel('C:\pythonscript\KDL\ConcreteData.xlsx', names=HDNames)
=>Data = pd.read_excel('ConcreteData.xlsx', names=HDNames)

Thank your for your effor. I understand Keras more deelpy with your effor. 

Best regards.

**Comment by casijoe5231** [comment]
Hi Paul, thanks for your review and for bringing this to our attention. Sorry for the late response, but I've made the necessary changes in the code. Do check it out and let me know if the issue can be closed.
